#!/usr/bin/env python
"""The actor-like Rockstar gate: verify the proxy on tiles the actor MADE.

``splice_verify.py`` re-runs the halo finder on tiles drawn from the labelled
candidate pool -- HR, frozen seeds, interventions. Every one of those is a field
the proxy's training distribution has seen the likes of. The actor is not: a
fine-tuned generator moves through a family of fields nothing in the pool
represents, and a proxy can rank the whole pool correctly while being wrong
about precisely those. So the gate that authorizes fine-tuning is measured on
tiles GENERATED BY a probe_only fine-tuned checkpoint, spliced into held-out
frozen boxes, and re-run through the real Rockstar.

Two stages:

``select`` (GPU, minutes)
    Load the probe checkpoint (``train_sr2_direct.py --probe``), generate the
    held-out verify boxes with it, compute the arm's features against each
    box's frozen reference, and choose ``n_actor_checks`` tiles stratified the
    same way the splice plan is (``predicted_positive`` / ``high_uncertainty``
    / ``random``), spread over at least ``min_actor_boxes`` boxes. Writes the
    plan and the generated fields it needs.
``run`` (CPU, hours -- one array task per check)
    Splice one actor tile into its frozen box, run Rockstar on the complete
    periodic box, and append the measured ``dR`` next to the predicted one to
    ``actor_verification_<arm>.jsonl`` -- the file
    ``gate_catalog_proxy.actor_verification`` consumes. Missing results never
    count as a pass.

    python scripts/reward/actor_rockstar_verify.py --stage select --arm b
    python scripts/reward/actor_rockstar_verify.py --stage run --arm b --index 0
"""
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Dict, List, Mapping

import numpy as np
import torch

from _proxy_data import (  # noqa: E402
    ARMS, build_row_context, ensemble_delta, load_rows,
)
from _sr2_direct import (  # noqa: E402
    actor_config_of, add_direct_args, append_jsonl, banner, bins_of, boxes_of,
    candidate_tag, dataset_of, direct_root, load_direct_config,
    load_reward_models, read_jsonl, run_dir, tile_grid_of, write_json_atomic,
)
from splice_verify import (  # noqa: E402
    _box_summary, _pick_spread_over_boxes, candidate_dir,
)

from cosmo_sr.eval.rockstar import run_rockstar_on_field  # noqa: E402
from cosmo_sr.reward.catalog_proxy import ProxyEnsemble  # noqa: E402
from cosmo_sr.reward.tiles import direct_full_box_stats, splice_tiles  # noqa: E402


def plan_path(run: Path, arm: str) -> Path:
    return run / f"actor_plan_{arm}.json"


def results_path(run: Path, arm: str) -> Path:
    return run / f"actor_verification_{arm}.jsonl"


def probe_stage_dir(run: Path, arm: str) -> Path:
    return run / f"probe_{arm}"


def actor_field_path(run: Path, arm: str, box: str) -> Path:
    return probe_stage_dir(run, arm) / "actor_fields" / f"{box}.npy"


def _require_probe_checkpoint(run: Path, arm: str) -> Path:
    """The probe EMA checkpoint, verified to actually BE a probe.

    An unstamped checkpoint here would mean the tiles being verified were made
    by something other than the capped, offline-gated probe the criterion is
    about -- most likely a production run smuggled in by path.
    """
    ck = probe_stage_dir(run, arm) / "ema_generator.pt"
    if not ck.is_file():
        raise SystemExit(
            f"no probe checkpoint at {ck}; produced by "
            f"scripts/reward/train_sr2_direct.py --arm {arm} --probe")
    blob = torch.load(str(ck), map_location="cpu", weights_only=False)
    extra = dict(blob.get("extra") or {})
    if not bool(extra.get("probe_only")):
        raise SystemExit(
            f"{ck} is not stamped probe_only; the actor gate only means "
            "something when its tiles come from the capped probe run")
    if str(extra.get("arm", arm)) != str(arm):
        raise SystemExit(
            f"{ck} was trained for arm {extra.get('arm')!r}, not {arm!r}")
    del blob
    return ck


def _require_field_gates(run: Path, arm: str, agate: Mapping) -> None:
    """The probe must not have broken the field before its splices count.

    A probe that wrecked the density power spectrum can still move the proxy's
    features in ways Rockstar responds to; passing THAT sign check would
    validate nothing an actual actor run could use.
    """
    if not bool(agate.get("require_probe_field_gates", True)):
        return
    g = run / f"gate_probe_{arm}.json"
    if not g.is_file():
        raise SystemExit(
            f"actor_gate.require_probe_field_gates is set and {g} is missing; "
            f"produced by scripts/reward/score_sr2_direct.py with "
            f"--tag probe_{arm} (score the probe checkpoint's fields first)")
    doc = json.loads(g.read_text())
    if not bool(doc.get("passed", False)):
        raise SystemExit(
            f"the probe checkpoint failed the field gates ({g}); its splices "
            "would measure a broken field, not the proxy. Not selecting.")


# --------------------------------------------------------------------------- #
# select
# --------------------------------------------------------------------------- #
def _arm_f_tile_features(cfg, field, box: str, device) -> np.ndarray:
    """``(n_tiles, 20, R, R, R)`` arm-F critic inputs from an in-memory field.

    tile_features caches only arms a/b/c/e; arm F streams raw fields and so is
    built here from the same primitives the OFFLINE provider uses
    (:class:`_proxy_data.FieldArmFeatures`), including the valid-centre CIC
    region -- otherwise the verifier would score the actor on a different arm-F
    feature than the proxy was trained on.
    """
    from cosmo_sr.reward.sr2_adversarial import critic_input
    from _sr2_direct import (arm_f_valid_center, geometry_of, load_lr,
                             soft_config_of)

    grid = tile_grid_of(cfg)
    scfg = soft_config_of(cfg)
    scale = int(geometry_of(cfg).scale_factor)
    grid_mult = int(dict(cfg.get("adversarial", {})).get("density_grid_mult", 2))
    vc = arm_f_valid_center(cfg)
    lr = np.asarray(load_lr(cfg, box), dtype=np.float32)
    field = np.asarray(field, dtype=np.float32)
    blocks: List[np.ndarray] = []
    for t in range(grid.n_tiles):
        sx, sy, sz = grid.slices(t)
        ftile = torch.as_tensor(field[:, sx, sy, sz], device=device)
        lslice = tuple(slice(s.start // scale, s.stop // scale) for s in (sx, sy, sz))
        lrtile = torch.as_tensor(lr[:, lslice[0], lslice[1], lslice[2]], device=device)
        ci = critic_input(lrtile.unsqueeze(0), ftile.unsqueeze(0),
                          cellsize_kpc_h=float(scfg.cellsize_kpc_h),
                          dis_norm_kpc_h=float(scfg.dis_norm_kpc_h),
                          grid_mult=grid_mult, valid_center=vc)
        blocks.append(ci[0].cpu().numpy())
    return np.stack(blocks, axis=0)


def _arm_feature_block(cfg, field, frozen, box: str, device, arm: str) -> np.ndarray:
    """One arm's per-tile feature block for the verifier, for EVERY arm.

    ``tile_features`` returns blocks for a/b/c/e only: arm D reads arm C's token
    grid (its live extractor IS arm C's), and arm F streams raw fields. Indexing
    ``tile_features(...)[arm]`` therefore KeyErrors on 'd' and 'f' -- which is
    why those two arms could not be actor-verified at all.
    """
    from collect_catalog_proxy_data import tile_features

    if arm == "f":
        return _arm_f_tile_features(cfg, field, box, device)
    owner = "c" if arm == "d" else arm      # arm D reuses arm C's tokens
    return tile_features(cfg, field, frozen, device)[owner]


def stage_select(cfg, args, device) -> int:
    from collect_catalog_proxy_data import generate_field

    agate = dict(cfg.get("actor_gate", {}))
    acfg = actor_config_of(cfg)
    _, reward_t = load_reward_models(cfg)
    arm = args.arm
    run = run_dir(args.run_name, create=True)

    ck = _require_probe_checkpoint(run, arm)
    _require_field_gates(run, arm, agate)
    proxy_dir = run / f"proxy_{arm}"
    if not proxy_dir.is_dir():
        print(f">>> MISSING INPUT: {proxy_dir}")
        print(">>> produced by: scripts/reward/train_catalog_proxy.py")
        return 0
    ens = ProxyEnsemble.load(proxy_dir).freeze()

    verify_boxes = [str(b) for b in agate.get("verify_boxes", [])]
    held_out = set(boxes_of(cfg, "proxy_gate"))
    stray = sorted(set(verify_boxes) - held_out)
    if stray:
        raise SystemExit(
            f"actor_gate.verify_boxes contains non-held-out boxes {stray}; the "
            "gate is only evidence on boxes the proxy never fitted")

    seeds = [int(s) for s in dataset_of(cfg).get("frozen_seeds", [0])]
    base_seed = seeds[0] if seeds else 0
    frozen_tag = candidate_tag("frozen", seed=base_seed)

    # The frozen rows carry the box and per-tile reference counts the proxy's
    # delta needs; the actor rows borrow them because an actor tile has no
    # label -- that is the point of this gate.
    table = direct_root("proxy_data") / "rows.jsonl"
    rows_all = load_rows(table, require_complete=not args.allow_incomplete)
    frozen_rows = [r for r in rows_all
                   if r["box"] in set(verify_boxes) and r["tag"] == frozen_tag]
    by_box_tile = {(r["box"], int(r["tile_id"])): r for r in frozen_rows}
    if not frozen_rows:
        print(f">>> MISSING INPUT: no {frozen_tag} rows for {verify_boxes} in "
              f"{table}")
        print(">>> produced by: the label pipeline (submit_proxy_labels.sh)")
        return 0

    banner(f"generating {len(verify_boxes)} verify boxes with the probe: {ck}")
    actor_rows: List[Dict] = []
    feats_blocks: List[np.ndarray] = []
    for box in verify_boxes:
        if not (candidate_dir(box, frozen_tag) / "field.npy").is_file():
            print(f">>> MISSING INPUT: {candidate_dir(box, frozen_tag) / 'field.npy'}")
            print(">>> the run stage splices into this field; regenerate the "
                  ">>> frozen candidate without --drop-field")
            return 0
        field = generate_field(cfg, box, "actor", base_seed, alpha=0.0,
                               mode="both", checkpoint=str(ck), device=device)
        frozen = generate_field(cfg, box, "frozen", base_seed, alpha=0.0,
                                mode="both", checkpoint="", device=device)
        feats = _arm_feature_block(cfg, field, frozen, box, device, arm)

        out = actor_field_path(run, arm, box)
        out.parent.mkdir(parents=True, exist_ok=True)
        tmp = out.with_suffix(".npy.tmp.npy")
        np.save(tmp, np.asarray(field, dtype=np.float32))
        tmp.replace(out)

        for t in range(feats.shape[0]):
            ref = by_box_tile.get((box, t))
            if ref is None:
                continue
            r = dict(ref)
            r["source"], r["tag"] = "actor", f"probe_{arm}"
            actor_rows.append(r)
            feats_blocks.append(feats[t])
        del field, frozen

    feats_arr = np.stack(feats_blocks).astype(np.float64)
    ctx = build_row_context(frozen_rows + actor_rows)
    actor_idx = np.arange(len(frozen_rows), len(frozen_rows) + len(actor_rows))
    w_joint, w_occ = float(acfg.w_joint_reward), float(acfg.w_occ_reward)
    mean, std = ensemble_delta(
        ens.members, torch.as_tensor(feats_arr, dtype=torch.float64),
        ctx.index(actor_idx), reward_t, w_joint=w_joint, w_occ=w_occ)

    boxes_arr = np.asarray([r["box"] for r in actor_rows])
    usable = np.nonzero(np.isfinite(mean))[0]
    n_total = int(agate.get("n_actor_checks", 12))
    strata = [str(s) for s in agate.get("actor_strata",
                                        ("predicted_positive",
                                         "high_uncertainty", "random"))]
    per = max(1, n_total // max(len(strata), 1))
    rng = np.random.default_rng(int(args.seed))
    taken: set = set()
    plan: List[Dict] = []
    for k, name in enumerate(strata):
        want = per if k < len(strata) - 1 else n_total - per * (len(strata) - 1)
        if name == "predicted_positive":
            order = [int(i) for i in usable[np.argsort(-mean[usable])]]
        elif name == "high_uncertainty":
            order = [int(i) for i in usable[np.argsort(-std[usable])]]
        else:
            order = [int(i) for i in rng.permutation(usable)]
        for i in _pick_spread_over_boxes(order, boxes_arr, want, taken):
            taken.add(i)
            r = actor_rows[i]
            plan.append({
                "stratum": name,
                "box": r["box"], "tile_id": int(r["tile_id"]),
                "base_tag": frozen_tag,
                "actor_field": str(actor_field_path(run, arm, r["box"])),
                "predicted_dR": float(mean[i]),
                "predicted_std": float(std[i]),
            })

    doc = {
        "arm": arm, "run_name": args.run_name, "n_planned": len(plan),
        "probe_checkpoint": str(ck),
        "boxes": sorted({p["box"] for p in plan}),
        "strata": {s: sum(1 for p in plan if p["stratum"] == s) for s in strata},
        "frozen_tag": frozen_tag, "checks": plan,
    }
    write_json_atomic(plan_path(run, arm), doc)
    banner(json.dumps({k: v for k, v in doc.items() if k != "checks"}, indent=2))
    if len(doc["boxes"]) < int(agate.get("min_actor_boxes", 3)):
        print(f">>> WARNING: the plan spans {len(doc['boxes'])} boxes, below "
              f">>> the configured minimum {agate.get('min_actor_boxes', 3)}; "
              ">>> the gate will report n_actor_boxes as unmet.")
    print(f"  submit one array task per check: --stage run --index "
          f"0..{len(plan) - 1}")
    return 0


# --------------------------------------------------------------------------- #
# run
# --------------------------------------------------------------------------- #
def stage_run(cfg, args) -> int:
    acfg = actor_config_of(cfg)
    _, reward_t = load_reward_models(cfg)
    bins = bins_of(cfg["_reward"])
    d = cfg["_reward"]["data"]
    box_l = float(d.get("boxsize_mpc_h", 100.0))
    grid = tile_grid_of(cfg)
    arm = args.arm
    run = run_dir(args.run_name, create=True)

    p = plan_path(run, arm)
    if not p.is_file():
        print(f">>> MISSING INPUT: {p}")
        print(">>> produced by: actor_rockstar_verify.py --stage select")
        return 0
    plan = json.loads(p.read_text())["checks"]
    if args.index >= len(plan):
        print(f">>> array index {args.index} is beyond the {len(plan)}-check "
              "plan; nothing to do.")
        return 0
    item = plan[int(args.index)]

    out = results_path(run, arm)
    if out.is_file() and args.reuse:
        done = {(r["box"], int(r["tile_id"])) for r in read_jsonl(out)}
        if (item["box"], int(item["tile_id"])) in done:
            banner(f"actor check {args.index} already verified; nothing to do.")
            return 0

    base_dir = candidate_dir(item["box"], item["base_tag"])
    actor_npy = Path(item["actor_field"])
    if not (base_dir / "field.npy").is_file():
        print(f">>> MISSING INPUT: {base_dir / 'field.npy'}")
        print(">>> produced by: collect_catalog_proxy_data.py --stage generate")
        return 0
    if not actor_npy.is_file():
        print(f">>> MISSING INPUT: {actor_npy}")
        print(">>> produced by: actor_rockstar_verify.py --stage select")
        return 0
    frozen_report = base_dir / "label_report.json"
    if not frozen_report.is_file():
        print(f">>> MISSING INPUT: {frozen_report}")
        print(">>> produced by: collect_catalog_proxy_data.py --stage label")
        return 0
    before_counts = json.loads(frozen_report.read_text())["full_box"]

    t0 = time.time()
    banner(f"actor check {args.index}: {item['box']} tile {item['tile_id']} <- "
           f"probe_{arm} ({item['stratum']})")
    base = np.load(base_dir / "field.npy", mmap_mode="r")
    donor = np.load(actor_npy, mmap_mode="r")
    field = splice_tiles(np.asarray(base), np.asarray(donor),
                         [int(item["tile_id"])], grid)
    del base, donor

    work = run / "actor_splices" / (
        f"{arm}_{args.index:02d}_{item['box']}_t{item['tile_id']}")
    cat = run_rockstar_on_field(
        field, work, tag=f"actor{args.index:02d}",
        boxsize_kpc_h=box_l * 1000.0, redshift=float(d.get("redshift", 0.0)),
        overwrite=not args.reuse)
    del field
    for g in Path(work).glob("*.gadget2"):
        g.unlink(missing_ok=True)
    for g in Path(work).glob("*.particles"):
        g.unlink(missing_ok=True)

    after = direct_full_box_stats(cat, bins)
    vol = box_l ** 3
    w_joint, w_occ = float(acfg.w_joint_reward), float(acfg.w_occ_reward)
    with torch.no_grad():
        s_before = _box_summary(before_counts, vol)
        s_after = _box_summary({k: after[k].tolist()
                                for k in ("n_sub", "n_host", "occ_numerator")},
                               vol)
        before_scores = reward_t.scores(s_before)
        after_scores = reward_t.scores(s_after)
        measured = {f"dR_{k[2:]}": float(after_scores[k][0] - before_scores[k][0])
                    for k in after_scores}
        measured["dR_combined"] = float(
            reward_t.combined(s_after, w_joint=w_joint, w_occ=w_occ)[0]
            - reward_t.combined(s_before, w_joint=w_joint, w_occ=w_occ)[0])

    row = dict(item)
    row.update({
        "index": int(args.index), "arm": arm,
        "measured_dR": measured["dR_combined"],
        "measured": measured,
        "sign_agrees": bool(np.sign(item["predicted_dR"])
                            == np.sign(measured["dR_combined"])),
        "n_objects_after": int(cat.n),
        "full_box_after": {k: after[k].tolist() for k in
                           ("n_sub", "n_host", "occ_numerator", "occupation")},
        "full_box_before": before_counts,
        "catalog_path": str(getattr(cat, "path", "")),
        "wall_min": (time.time() - t0) / 60.0,
    })
    append_jsonl(out, row)
    banner(f"predicted {item['predicted_dR']:+.5g} vs measured "
           f"{measured['dR_combined']:+.5g}  -> "
           f"{'AGREE' if row['sign_agrees'] else 'DISAGREE'}   {out}")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    add_direct_args(ap)
    ap.add_argument("--stage", required=True, choices=("select", "run"))
    ap.add_argument("--arm", default="a", choices=list(ARMS))
    ap.add_argument("--index", type=int, default=0)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--device", default="")
    ap.add_argument("--reuse", action="store_true", default=True)
    ap.add_argument("--overwrite", dest="reuse", action="store_false")
    ap.add_argument("--allow-incomplete", action="store_true")
    args = ap.parse_args(argv)

    cfg = load_direct_config(args)
    if args.stage == "select":
        device = torch.device(args.device or
                              ("cuda" if torch.cuda.is_available() else "cpu"))
        return stage_select(cfg, args, device)
    return stage_run(cfg, args)


if __name__ == "__main__":
    raise SystemExit(main())
