#!/usr/bin/env bash
# Submit the density-fix evaluation pipeline as a SLURM dependency chain.
#
#   bash scripts/slurm/submit_dfix.sh                    # everything
#   STAGES="0 0b table" bash scripts/slurm/submit_dfix.sh   # the decisive part only
#   DRY=1 bash scripts/slurm/submit_dfix.sh              # print, do not submit
#   BOX=set15 OUT=runs/dmsr/dfix_set15 bash scripts/slurm/submit_dfix.sh
#
# Nothing runs on the submit host: this only calls sbatch.
#
# Shape of the chain:
#
#   0  (GPU)  full-box ruler, all four arms, caches the fields   ─┬─> 1 (CPU) alpha
#   0b (GPU)  same ruler at the training window size              │
#   3  (GPU)  context oracle      ─┐                              │
#   4  (GPU)  receptive field      ├─ siblings, no interdependence │
#   6  (GPU)  best-of-K           ─┘                              │
#                                                                 └─> table (CPU)
#
# Stages 0/0b/3/4/6 are siblings so they queue concurrently; only Stage 1 needs
# Stage 0's cached fields. The table waits for everything but is not gated on it
# -- it prints an explicit "not run" line for each missing stage, which is more
# useful than no table.
#
# Gate checks live *inside* the jobs. A missing input exits 0 with a message, so
# the rest of the chain still starts and each stage reports its own skip instead
# of the whole chain dying in DependencyNeverSatisfied with no explanation.
#
# Splitting by resource is deliberate: Stage 1 and the table read saved .npy and
# .json only, so asking for a GPU would just queue them behind real work.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT="${PROJECT:-$(cd "$HERE/../.." && pwd)}"
cd "$PROJECT"

: "${OUT:=runs/dmsr/dfix}"
: "${BOX:=set14}"
: "${STAGES:=0 0b 1 3 4 6 table}"
: "${DRY:=0}"

# --- configuration channel ------------------------------------------------- #
# NO `sbatch --export` ANYWHERE IN THIS FILE, in any form. On this cluster an
# explicit export list (`--export=ALL,OUT=x` or `--export=OUT=x` alike) makes
# sbatch set SLURM_GET_USER_ENV=1; slurmd then tries to rebuild the login
# environment on the compute node, the lookup fails, and the job is requeued and
# held with `(user env retrieval failed requeued held)`, stranding everything
# behind it. Measured on the sibling TTS chain, jobs 22184 and 22243.
#
# Config therefore goes into a file that each job sources, passed as a
# positional argument to the batch script -- arguments travel through the job
# record untouched. One file per submission, timestamped, so re-running the
# submitter cannot retroactively change the config of a job still queued.
ENVDIR="$PROJECT/runs/.dfix_env"
mkdir -p "$ENVDIR"
ENVFILE="$ENVDIR/$(date +%Y%m%d-%H%M%S)-$$.sh"
{
    echo "# generated by submit_dfix.sh on $(date '+%F %T')"
    printf 'export OUT=%q\n' "$OUT"
    printf 'export BOX=%q\n' "$BOX"
    printf 'export PROJECT=%q\n' "$PROJECT"
    for var in DATA DEVICE N_STEPS ARMS PROBE_ARM TILE HALO LR_CROP CONTEXTS \
               WINDOW RF_STEPS ALPHAS COMPONENTS ALPHA_LABELS K REGIONS \
               TRAIN_BOX CONDA_ENV; do
        # A file, unlike --export, has no trouble with spaces, so lists stay in
        # their natural form here.
        [[ -n "${!var:-}" ]] && printf 'export %s=%q\n' "$var" "${!var}"
    done
} > "$ENVFILE"

# Inherited SLURM_* from a surrounding salloc/srun shell would otherwise be
# merged into the new jobs (SLURM_CPUS_PER_TASK and friends really do change how
# steps are sized), so scrub them here before submitting.
if [[ -n "${SLURM_JOB_ID:-}" ]]; then
    echo "note: submitting from inside job ${SLURM_JOB_ID}; its SLURM_* variables" \
         "are scrubbed, not inherited by the new jobs."
fi
while read -r _v; do unset "$_v"; done < <(compgen -v | grep '^SLURM_' || true)
unset SBATCH_EXPORT SBATCH_GET_USER_ENV

has() { [[ " $STAGES " == *" $1 "* ]]; }

# submit() runs in a command substitution, so a shell-variable counter would not
# survive the subshell; DRY ids come from a file instead.
_DRY_COUNTER="$(mktemp)"; echo 2000 > "$_DRY_COUNTER"
trap 'rm -f "$_DRY_COUNTER"' EXIT

submit() {  # submit <dependency-or-empty> <script> [VAR=value ...]
    local dep="$1" script="$2"; shift 2
    local args=(--parsable)
    [[ -n "$dep" ]] && args+=(--dependency=afterok:"$dep")
    if [[ "$DRY" == "1" ]]; then
        # Distinct plausible ids, so the dependency wiring below is actually
        # exercised rather than collapsing to "after nothing".
        local id=$(( $(cat "$_DRY_COUNTER") + 1 ))
        echo "$id" > "$_DRY_COUNTER"
        { printf 'sbatch'; printf ' %q' "${args[@]}" "$script" "$ENVFILE" "$@"
          printf '\n'; } >&2
        echo "$id"
        return
    fi
    # Everything after the script name is an argument to the *job*, not to
    # sbatch: the env file first, then any per-job overrides.
    sbatch "${args[@]}" "$script" "$ENVFILE" "$@"
}

join_deps() {  # colon-joined list of the non-empty job ids given
    local out=""
    for id in "$@"; do
        [[ -n "$id" ]] && out="${out:+$out:}$id"
    done
    echo "$out"
}

echo "project : $PROJECT"
echo "out     : $OUT"
echo "box     : $BOX"
echo "stages  : $STAGES"
echo "config  : $ENVFILE"
echo

J0=""; J0B=""; J1=""; J3=""; J4=""; J6=""
if has 0; then
    J0="$(submit "" "$HERE/dfix_stage0_ceiling.sbatch")"
    echo "stage 0   full-box ruler (GPU)      -> job $J0"
fi
if has 0b; then
    J0B="$(submit "" "$HERE/dfix_stage0_tile8.sbatch")"
    echo "stage 0b  ruler at train window(GPU)-> job $J0B"
fi
if has 3; then
    J3="$(submit "" "$HERE/dfix_stage3_context.sbatch")"
    echo "stage 3   context oracle (GPU)      -> job $J3"
fi
if has 4; then
    J4="$(submit "" "$HERE/dfix_stage4_rf.sbatch")"
    echo "stage 4   receptive field (GPU)     -> job $J4"
fi
if has 6; then
    J6="$(submit "" "$HERE/dfix_stage6_bestofk.sbatch")"
    echo "stage 6   best-of-K (GPU)           -> job $J6"
fi
if has 1; then
    # The only real dependency: Stage 1 reads the fields Stage 0 cached.
    J1="$(submit "$J0" "$HERE/dfix_stage1_alpha.sbatch")"
    echo "stage 1   residual alpha (CPU)      -> job $J1  (after ${J0:-nothing})"
fi
if has table; then
    DEPS="$(join_deps "$J0" "$J0B" "$J1" "$J3" "$J4" "$J6")"
    JT="$(submit "$DEPS" "$HERE/dfix_table.sbatch")"
    echo "table     summary + figure (CPU)    -> job $JT  (after ${DEPS:-nothing})"
fi

echo
echo "watch:   squeue -u \$USER -o '%.10i %.16j %.9P %.2t %.10M %R'"
echo "results: $OUT/summary.md   (redraw any time: sbatch $HERE/dfix_table.sbatch)"
