#!/bin/bash
# Submit the Lagrangian-only-critic sweep: 4 sibling GPU jobs, no dependencies,
# so they queue concurrently and a failure costs one arm.
#
# WHAT THIS TESTS. Every adversarial arm run so far fed the critic a density
# channel built by the wrap-in-crop CIC deposit, measured at r = 0.080 against
# the true density of a 64^3 crop. The lambda ladder (0 / 3e-4 / 1e-3 / 3e-3 /
# 3e-2) was therefore run on a critic whose input was part signal, part noise,
# and it came out flat: val_rk_high 0.825-0.840 across a 100x weight range. SR2
# has no density channel at all -- its critic eats the Lagrangian field directly
# (map2map/train.py:364-371) -- and reaches density P/P_HR 0.977, sigma 1.0001 on
# our own set14 reproduction. These four arms remove the channel and then walk
# the two knobs that were never separable from it.
#
#   scripts/slurm/submit_lagonly.sh
#   DRY=1 scripts/slurm/submit_lagonly.sh                    # print, do not submit
#   ARMS="t13_lagonly_l003 t13_lagonly_bp4_l003" scripts/slurm/submit_lagonly.sh
set -euo pipefail

SLURM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT="$(cd "$SLURM_DIR/../.." && pwd)"
cd "$PROJECT"

ARMS="${ARMS:-t13_lagonly_l003 t13_lagonly_bp4_l003 t13_lagonly_bp4_l03 t13_lagonly_bp4_l03_flow01}"
ZFS="${ZFS:-/zfsauton/scratch/yixiz}"
ROOT="$ZFS/DMSR/cosmo_sr_runs/dmsr/lagonly"
LOGS="$ROOT/logs"
mkdir -p "$LOGS"

# One timestamped env file per submission, passed as a POSITIONAL argument.
# Never `sbatch --export`: any explicit export list sets SLURM_GET_USER_ENV=1 and
# the job is requeued and HELD on this cluster.
STAMP="$(date +%Y%m%d-%H%M%S)"
ENVF="$LOGS/env-$STAMP.sh"
cat > "$ENVF" <<ENV
# Generated by submit_lagonly.sh at $STAMP -- one file per submission.
PROJECT=$PROJECT
ZFS=$ZFS
LOGS=$LOGS
WANDB_MODE=${WANDB_MODE:-online}
ENV
echo "env file: $ENVF"

sub() {  # echo + (unless DRY) run, returning a parsable job id
    if [[ "${DRY:-0}" == "1" ]]; then echo "DRY: sbatch $*" >&2; echo "DRYID"; else sbatch --parsable "$@"; fi
}

# Do not leak this shell's SLURM_* into sbatch (breaks env retrieval when
# submitting from inside an allocation).
for v in $(env | grep -oE '^SLURM_[A-Z_]+' || true); do unset "$v"; done

# Arms that already have a queued or running job of the same name. Two jobs for
# one arm share a run_dir, so they would corrupt each other's metrics.csv and
# ckpt_best.pt -- this is a correctness guard, not a courtesy. SKIP_QUEUED=0
# disables it (e.g. deliberately re-running an arm into a fresh run_dir).
QUEUED=""
if [[ "${SKIP_QUEUED:-1}" == "1" ]] && command -v squeue >/dev/null 2>&1; then
    QUEUED="$(squeue -u "${USER:-$(id -un)}" -h -o '%j' 2>/dev/null \
              | sed -n 's/^lag_/t13_lagonly_/p' | sort -u || true)"
    [[ -n "$QUEUED" ]] && echo "already queued/running: $(echo $QUEUED)"
fi

declare -a IDS=()
declare -a SKIPPED=()
for arm in $ARMS; do
    cfg="configs/dmsr/$arm.yaml"
    if [[ ! -r "$cfg" ]]; then
        echo ">>> no config $cfg -- skipping $arm" >&2
        continue
    fi
    if [[ -n "$QUEUED" ]] && grep -qx "$arm" <<<"$QUEUED"; then
        echo "skip $arm -- already queued/running (SKIP_QUEUED=0 to override)"
        SKIPPED+=("$arm"); continue
    fi
    if [[ "${SKIP_DONE:-1}" == "1" && -s "runs/dmsr/${arm}_s0/metrics.csv" ]]; then
        echo "skip $arm -- runs/dmsr/${arm}_s0/metrics.csv already exists"
        echo "     (SKIP_DONE=0 to overwrite; check it is not a live run first)"
        SKIPPED+=("$arm"); continue
    fi
    id=$(sub --job-name="lag_${arm#t13_lagonly_}" \
             scripts/slurm/lagonly_train_gpu.sbatch "$ENVF" ARM="$arm")
    echo "submitted $arm -> job $id (GPU, general)"
    IDS+=("$id:$arm")
done

if [[ ${#IDS[@]} -eq 0 ]]; then
    echo
    echo "nothing submitted -- every requested arm was already queued or already has results."
    exit 0
fi

cat <<EOF

=== monitor ===
EOF
for entry in "${IDS[@]}"; do
    echo "  ${entry#*:}"
    echo "      tail -F $LOGS/slurm-lagonly-${entry%%:*}.out"
done
cat <<EOF

  READ THE FIRST LOG BEFORE TRUSTING THE SWEEP. The line to check is

      [adv] lambda_flow=... lambda_adv=... bp_steps=... density_mode='off' (critic in_channels=3)

  If in_channels is 11, PyYAML coerced \`off\` to the boolean False somewhere and
  the arm is silently the OLD density critic (tests/dmsr/test_lagonly_arms.py
  pins this, but the log is the ground truth).

=== results ===
  metrics : runs/dmsr/<arm>_s0/metrics.csv
  compare : val_density_power_error / val_density_rk_high are on the vc32 ruler,
            so they ARE comparable to runs/dmsr/t13_fix_vc32_s0 (the A/B partner)
            and NOT to any arm without critic.valid_center: 32.
  calibr. : grad_ratio_adv_flow (logged every 200 steps) recalibrates the weight
            ladder for the 3-channel critic; it is exactly linear in lambda_adv.

=== the measurement that actually decides ===
  Training metrics cannot answer the density question -- Stage 0 can. After an arm
  finishes, put it on the full-box ruler, ONE ARM PER JOB (job 22252 died at ~8 h
  having done 1 of 4 arms at 5.3 GPU-h per full-box draw):

      ARMS="t13_lagonly_l003:runs/dmsr/t13_lagonly_l003_s0" \\
          sbatch scripts/slurm/dfix_stage0_ceiling.sbatch
EOF
