#!/usr/bin/env bash
# Submit the whole SR2 test-time-scaling pipeline as a SLURM dependency chain.
#
#   bash scripts/slurm/submit_tts.sh                       # everything, K = 16
#   K=32 OUT=runs/tts_k32 bash scripts/slurm/submit_tts.sh
#   STAGES="1 viz" bash scripts/slurm/submit_tts.sh        # just those
#   DRY=1 bash scripts/slurm/submit_tts.sh                 # print, do not submit
#
# Nothing runs on the submit host: this only calls sbatch. Each job depends on
# the previous with `afterok`, and the gate checks live *inside* the jobs -- a
# failed gate exits 0 with a message, so the rest of the chain still starts and
# each stage reports its own skip instead of the whole chain dying in
# DependencyNeverSatisfied.
#
# Stage 4's two arms (gradient, CEM) and Stage 5 are siblings: all three depend
# on Stage 2 and none on each other, so they run concurrently if the queue
# allows. Stage 6 and the figures wait for all of them.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT="${PROJECT:-$(cd "$HERE/../.." && pwd)}"
cd "$PROJECT"

: "${OUT:=runs/tts}"
: "${K:=16}"
: "${STAGES:=1 2 4 5 6 viz}"
: "${DRY:=0}"

# --- configuration channel ------------------------------------------------- #
# NO `sbatch --export` ANYWHERE IN THIS FILE, in any form. On this cluster an
# explicit export list (`--export=ALL,K=16` or `--export=K=16` alike) makes
# sbatch set SLURM_GET_USER_ENV=1; slurmd then tries to rebuild the login
# environment on the compute node, the lookup fails, and the job is requeued and
# held with `(user env retrieval failed requeued held)`, stranding the chain
# behind it. Measured twice: jobs 22184 and 22243. The jobs that do work on this
# cluster pass no --export at all.
#
# So the config goes into a file that each job sources, and the path is a
# positional argument to the batch script -- arguments travel through the job
# record untouched. One file per submission, timestamped, so re-running the
# submitter cannot retroactively change the config of a job still queued.
ENVDIR="$PROJECT/runs/.tts_env"
mkdir -p "$ENVDIR"
ENVFILE="$ENVDIR/$(date +%Y%m%d-%H%M%S)-$$.sh"
{
    echo "# generated by submit_tts.sh on $(date '+%F %T')"
    printf 'export OUT=%q\n' "$OUT"
    printf 'export K=%q\n' "$K"
    printf 'export PROJECT=%q\n' "$PROJECT"
    for var in DATA MODEL DEVICE TRAIN_BOXES VAL_BOXES TEST_BOXES KEEP CHUNK \
               STRIDE LAM_OVERLAP STITCH SLICE_BOX CONDA_ENV; do
        # A file, unlike --export, has no trouble with spaces, so box lists stay
        # in their natural form here.
        [[ -n "${!var:-}" ]] && printf 'export %s=%q\n' "$var" "${!var}"
    done
} > "$ENVFILE"

# Inherited SLURM_* from a surrounding salloc/srun shell would otherwise be
# merged into the new jobs (SLURM_CPUS_PER_TASK and friends really do change how
# steps are sized). Scrub them here so sbatch cannot see them.
if [[ -n "${SLURM_JOB_ID:-}" ]]; then
    echo "note: submitting from inside job ${SLURM_JOB_ID}; its SLURM_* variables" \
         "are scrubbed, not inherited by the new jobs."
fi
while read -r _v; do unset "$_v"; done < <(compgen -v | grep '^SLURM_' || true)
unset SBATCH_EXPORT SBATCH_GET_USER_ENV

has() { [[ " $STAGES " == *" $1 "* ]]; }

# submit() is called in a command substitution, so a shell variable counter
# would not survive the subshell; DRY ids come from a file instead.
_DRY_COUNTER="$(mktemp)"; echo 1000 > "$_DRY_COUNTER"
trap 'rm -f "$_DRY_COUNTER"' EXIT

submit() {  # submit <dependency-or-empty> <script> [VAR=value ...]
    local dep="$1" script="$2"; shift 2
    local args=(--parsable)
    [[ -n "$dep" ]] && args+=(--dependency=afterok:"$dep")
    if [[ "$DRY" == "1" ]]; then
        # Hand back distinct plausible job ids so the dependency wiring below is
        # actually exercised instead of collapsing to "after nothing".
        local id=$(( $(cat "$_DRY_COUNTER") + 1 ))
        echo "$id" > "$_DRY_COUNTER"
        { printf 'sbatch'; printf ' %q' "${args[@]}" "$script" "$ENVFILE" "$@"
          printf '\n'; } >&2
        echo "$id"
        return
    fi
    # Everything after the script name is an argument to the *job*, not to
    # sbatch: the env file first, then any per-job overrides.
    sbatch "${args[@]}" "$script" "$ENVFILE" "$@"
}

join_deps() {  # colon-joined list of the non-empty job ids given
    local out=""
    for id in "$@"; do
        [[ -n "$id" ]] && out="${out:+$out:}$id"
    done
    echo "$out"
}

echo "project : $PROJECT"
echo "out     : $OUT"
echo "K       : $K"
echo "stages  : $STAGES"
echo "config  : $ENVFILE"
echo

J1=""; J2=""; J4=""; J4C=""; J5=""; J6=""
if has 1; then
    J1="$(submit "" "$HERE/tts_stage1_oracle.sbatch")"
    echo "stage 1  oracle audit        -> job $J1"
fi
if has 2; then
    J2="$(submit "$J1" "$HERE/tts_stage2_verifier.sbatch")"
    echo "stage 2  verifier            -> job $J2  (after $J1)"
fi
if has 4; then
    J4="$(submit "$J2" "$HERE/tts_stage4_refine.sbatch" "ARM=grad")"
    echo "stage 4  refine (gradient)   -> job $J4  (after $J2)"
    J4C="$(submit "$J2" "$HERE/tts_stage4_refine.sbatch" "ARM=cem")"
    echo "stage 4  refine (CEM control)-> job $J4C (after $J2)"
fi
if has 5; then
    J5="$(submit "$J2" "$HERE/tts_stage5_global.sbatch")"
    echo "stage 5  global joint tiling -> job $J5  (after $J2)"
fi

DEPS="$(join_deps "$J4" "$J4C" "$J5")"
[[ -z "$DEPS" ]] && DEPS="$(join_deps "$J2" "$J1")"
if has 6; then
    J6="$(submit "$DEPS" "$HERE/tts_stage6_table.sbatch")"
    echo "stage 6  final table         -> job $J6  (after ${DEPS:-nothing})"
fi
if has viz; then
    VDEP="$(join_deps "$J6")"; [[ -z "$VDEP" ]] && VDEP="$DEPS"
    JV="$(submit "$VDEP" "$HERE/tts_viz.sbatch")"
    echo "viz      figures             -> job $JV  (after ${VDEP:-nothing})"
    JVS="$(submit "$VDEP" "$HERE/tts_viz_slices.sbatch")"
    echo "viz      density slices      -> job $JVS (after ${VDEP:-nothing})"
fi

echo
echo "watch:   squeue -u \$USER -o '%.10i %.16j %.9P %.2t %.10M %R'"
echo "results: $OUT/{oracle,verifier,stage4,stage4_cem,stage5,final,figures}"
