"""Conditioning features built on the LR Lagrangian lattice."""
from __future__ import annotations

from .bound_discriminator import (
    G_MPC_KMS2_PER_MSUN, SetStats, mann_whitney_auc, member_ids,
    particles_at, set_statistics, specific_potential, unwrap_periodic,
)
from .cond_spread import (
    RidgeSolver,
    apply_random_features,
    band_power_fraction,
    gaussian_lowpass,
    hann_window,
    local_scale,
    neighbourhood_matrix,
    r2_uncentred,
    radial_cross_spectra,
    random_feature_map,
    ridge_fit,
    ridge_predict,
    wavenumbers,
)
from .host_crops import (
    CropFrame,
    auc,
    block_reduce,
    crop_frame,
    flat_to_sites,
    lagrangian_radius_sites,
    periodic_site_centre,
    resample_report,
    roc_curve,
    sites_to_flat,
    to_crop_coords,
)
from .lagrangian_host import (
    HostTable,
    LagrangianGrid,
    LagrangianHostFeatures,
    build_host_features,
    lagrangian_lattice_positions,
    normalization_report,
)

__all__ = [
    "CropFrame",
    "RidgeSolver",
    "HostTable",
    "LagrangianGrid",
    "LagrangianHostFeatures",
    "apply_random_features",
    "auc",
    "band_power_fraction",
    "block_reduce",
    "build_host_features",
    "crop_frame",
    "flat_to_sites",
    "gaussian_lowpass",
    "hann_window",
    "lagrangian_lattice_positions",
    "lagrangian_radius_sites",
    "local_scale",
    "neighbourhood_matrix",
    "normalization_report",
    "periodic_site_centre",
    "r2_uncentred",
    "radial_cross_spectra",
    "random_feature_map",
    "resample_report",
    "ridge_fit",
    "ridge_predict",
    "roc_curve",
    "sites_to_flat",
    "to_crop_coords",
    "wavenumbers",
    "G_MPC_KMS2_PER_MSUN",
    "SetStats",
    "mann_whitney_auc",
    "member_ids",
    "particles_at",
    "set_statistics",
    "specific_potential",
    "unwrap_periodic",
]
